services:
  db:
    image: mysql
    container_name: BDPRUEBATECNICA
    ports: 
      - "3306:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: "pruebatecnica"
      MYSQL_DATABASE: "transportept"
    volumes: 
      - ./schemas:/var/lib/mysql
